### PR TITLE
Add sampleRate config option

### PR DESCRIPTION
**Pull request by LewisJEllis**
Basically the same thing as getsentry/raven-js#885

/cc @benvinegar @dcramer

### CODE REVIEW

**Comment by LewisJEllis** [comment]
Added tests. Feels kinda messy compared to the raven-js parallels with the nice sinon setup :/

**Comment by MarkHerhold** [comment]
Sorry for the dumb question, but what is the use-case for this?

**Comment by benvinegar** [comment]
@MarkHerhold – This is analogous to rate-limiting, except the rate-limiting occurs on the client, not the server. This has the upside of sending less traffic to sentry.io ($) / your own Sentry server at the expense of losing data.

Sampling is often necessary for very high traffic applications.

**Comment by MarkHerhold** [comment]
Ah, so this would be for applications that are utilizing Sentry as a logging service rather than an error tracker?

**Comment by benvinegar** [comment]
It's more like – if you have 1 million active users, and they all hit the same error, do you really need 1 million error reports to be sent? Probably not.

So, if you have an app with a really huge active user count, you can probably safely suppress a fraction of error reports using `sampleRate` to save bandwidth, $, etc.

**Comment by MarkHerhold** [comment]
Got it, thanks!

**Pull request merged**
