### PR TITLE
Add column number to Sentry payload

### PR DESCRIPTION
**Pull request by Ngo-The-Trung**

### CODE REVIEW

**Comment by zehua** [comment]
👍

**Comment by LewisJEllis** [comment]
Huh, I never even noticed we weren't already doing this. Thanks!

**Comment by zehua** [comment]
Thanks. When do you plan to release a new version? We want to make sure of this fix in our app.

**Comment by LewisJEllis** [comment]
This merged into master which is on the beta pipeline, but I'm releasing a 0.12.2 patch today that I could backport this into if you need it.

**Comment by zehua** [comment]
Thanks. That would definitely help.

**Comment by LewisJEllis** [comment]
@zehua @Ngo-The-Trung published this in v0.12.2.

**Comment by Ngo-The-Trung** [comment]
Thanks for the heads up @LewisJEllis

**Pull request merged**
