### PR TITLE
Add unhandledRejection handler

### PR DESCRIPTION
**Pull request by LewisJEllis**

### CODE REVIEW

**Comment by benvinegar** [comment]
I strongly feel this should be an option, and not done by default. Also because a lot of promise libraries return non-error values for "reason", which makes entries in Sentry look bad.

**Comment by LewisJEllis** [comment]
Added options parameter to `#install()` so you have to do:
```
Raven.config(dsn).install({ unhandledRejection: true });
```

**Comment by LewisJEllis** [comment]
Figured you might say that, but hadn't come up with a good way to deal with older nodes that don't have Promises/don't have Promises linked to `unhandledRejection`. Realized this morning that I can just `process.emit('unhandledRejection', ...)` 

Added tests.

**Comment by LewisJEllis** [comment]
Yea agreed, thought right now `#install` in raven-js doesn't take a callback at all (which we do here carried over from `#patchGlobal`), and the signature/behavior of that callback are kind of wonky here, but I've not yet figured out how it should be instead.

**Comment by jjinux** [comment]
Hmm, I don't think this is in the documentation.

**Comment by kamilogorek** [comment]
It is https://docs.sentry.io/clients/node/usage/#promises

**Pull request merged**
