### PR TITLE
feat(mergeContext): support deep merge

### LINKED ISSUE #228: mergeContext is shallow and could be better if it went deeper
Right now it just throws our `extend` helper at the context object, which is a shallow non-recursive merge, so:
```javascript
Raven.setContext({
  user: {
    username: 'lewis',
  }
});
Raven.mergeContext({
  user: {
    email: 'lewis@...'
  }
});
console.log(Raven.getContext().user);
```
currently gives us:
```
{
  email: 'lewis@...'
}
```
but we might prefer/expect to get:
```
{
  username: 'lewis',
  email: 'lewis@...'
}
```
It only does mergey stuff in not clobbering any keys on the ctx other than `user`, but it's just replacing the old value of user with the new one.

Right now to accomplish this, we need to do something like:
```javascript
var currUserCtx = Raven.getContext().user;
var newUser = goDoOurOwnMerge(currUserCtx, { email: 'lewis@...' });
Raven.mergeContext({ user: newUser });
```

The context data needs to be json-serializable anyway and we use json-stringify-safe, but we should also be careful not to let merging trip on recursion/circular reference problems. I think just going one level deeper should keep this simple and still make `mergeContext` significantly more helpful, but I haven't really ruled out other options.

/cc @benvinegar @MaxBittker for thoughts

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #228

### CODE REVIEW

**Comment by MaxBittker** [comment]
hi @patrickhulce - I appreciate this patch but we're not confident on moving on it right now because of concerns about breaking existing behavior and very deeply nested / circular object tar pits, as well as because of diverging from the raven-js behavior. Might revisit this in the future though

**Comment by patrickhulce** [comment]
alright thanks for the heads up @MaxBittker I implemented it because I needed it, so I'm fine to leave it, lmk if there's any movement on this in the future

**Comment by arabold** [comment]
I'm certainly voting for having this merged in one form or the other in the next major release. Specifically when using `tags` and `extras` it doesn't make sense that `mergeContext` overwrites all previously set values. That's not a merge and actually counterintuitive IMO. A simple fix without processing objects recursively would be to merge `tags` and `extras` individually like this:

```js
function mergeContext(ctx) {
  const oldCtx = this.getContext();
  if (ctx.user) {
    oldCtx.user = ctx.user; // don't merge the user info
  }
  extend(oldCtx.tags, ctx.tags);
  extend(oldCtx.extras, ctx.extras);
  return this;
},
```

I'm happy to provide an updated and tested PR if this would be an option for you.

**Comment by patrickhulce** [comment]
> Specifically when using tags and extras it doesn't make sense that mergeContext overwrites all previously set values.

Agree 100%, I mistakenly believed they would not be overridden when originally using the API. Not sure about the special case handling of no merge for user :), but I'd be happy to update this PR to just shallow extension in @arabold's comment when we're ready.

**Comment by arabold** [comment]
The thought behind not merging the `user` is that you might switch from one user account to another, e.g. if the user logs in and converts from being an anonymous user a specific one. Typically you wouldn't want to merge user properties in those cases.

**Comment by patrickhulce** [comment]
I recognize the `mergeContext({user: null})` workaround isn't as nice for unsetting a user, but it feels a bit odd to have it consistently merge everything except user properties (especially since the motivating example in #228 is for merging user properties). I digress though, perhaps this discussion should move to the issue itself?

**Comment by kamilogorek** [comment]
Closing this for now until we settle on one solution. Let's move discussion to https://github.com/getsentry/raven-node/pull/330 per @patrickhulce comment.

**Pull request closed without merging**
