### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by MichielDeMey**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
wtf how was this not broken for everyone all the time?

**Comment by MichielDeMey** [comment]
I'm asking myself the exact same thing. :)

**Comment by ruimarinho** [comment]
Nice catch! Turns out `--undefined` makes it a `NaN`.

**Comment by mattrobenolt** [comment]
I'm not entirely sure how it doesn't throw a `ReferenceError` though. Or maybe it did?

**Comment by ruimarinho** [comment]
Hmm, yeah, probably did. It would be cool to add a test for this :D

**Pull request merged**
