### PR TITLE
Add code coverage in test suit

### PR DESCRIPTION
**Pull request by willmendesneto**
Adding [istanbul](https://gotwarlost.github.io/istanbul/) for code coverage. After that a good idea can be add a badge about the test code coverage percentage in the repository (using services such as [https://coveralls.io/](https://coveralls.io/) ).

Opinions? Suggestions? Concerns ?

### CODE REVIEW

**Comment by willmendesneto** [comment]
@dcramer Can you take a look in this, please? https://travis-ci.org/getsentry/raven-node/jobs/133685102
screen shot 2016-05-29 at 5 34 19 pm

**Comment by dcramer** [comment]
@willmendesneto I think when that happens you just have to retry the build (via Travis)

@benvinegar i assume this is good?

**Comment by willmendesneto** [comment]
@dcramer I'm not able to retry the build. Can you do it, please?

**Comment by benvinegar** [comment]
👍

**Pull request merged**
