### PR TITLE
Better recursive poison, perhaps?

### PR DESCRIPTION
**Pull request by connor4312**
Unit tests pass... seems to work, but I wouldn't bet my life that it covers every edge case.

In regards to #91

### CODE REVIEW

**Comment by moll** [comment]
The latest code I pushed to https://github.com/isaacs/json-stringify-safe might do the trick in 27 lines. Would you mind giving it a try? Thanks!

**Comment by benvinegar** [comment]
Hey, I'd love to get this PR merged. I know it's been some time and you may barely remember this, but is there any chance you can add tests?

**Comment by connor4312** [comment]
Hey, sure. I'll take a look at updating this when I get a moment.

**Comment by benvinegar** [comment]
Closed in favor of #182

**Pull request closed without merging**
